spring:
  #数据源配置
  datasource:
    #数据库地址
    url: jdbc:mysql://localhost:3306/news?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC

    #用户名
    username: news

    #密码
    password: FpKZPcbF85SNzRms

#日志配置
logging:
  level:
    #日志配置
    #还可以单独指定某个包下面日志级别
    root: warn
    #  file:
    #    # 日志文件路径
    #    # 这是相对当前应用路径
    #    name: log/news-api-sp.log

    # 绝对路径
    #name: /var/log/news-api-sp.log

# sa-token配置
#sa-token:
#  # 是否输出操作日志
#  is-log: false