server:
  port: 8080
spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null #不返回数据为空的字段给前端
    date-format: yyyy-MM-dd->HH:mm:ss  #设置返回到前端的日期格式
    time-zone: UTC  #时区
  servlet:
    #文件上传配置
    multipart:
      max-file-size: 500KB  #上传文件的最大大小
      max-request-size: 1024KB    # 一次请求最大大小，也就是说单个是500K，一次发几个文件的话不能超过此配置
  # redis 配置
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
mybatis-plus:
  configuration:
    #map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  # session ????????
#  session:
#    timeout: 86400
#    store-type: redis
#  # redis ??

#server:
#  port: 7529
#  servlet:
#    context-path: /api
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: isDelete # ????????????(since 3.3.0,????????????2)
#      logic-delete-value: 1 # ??????(??? 1)
#      logic-not-delete-value: 0 # ??????(??? 0)


logging:
  level:
    root: info
# sa-token配置
sa-token:
  #禁用cookie
  is-read-cookie: true

  # token名称 (同时也是cookie名称)
  token-name: authorization

  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: -1

  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒，这里设置为7天
  #active-timeout: -1

  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false

  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false

  # token风格，好像当前版本无效
  token-style: random-64

  # 是否输出操作日志
  is-log: true